server:
  port: 8888

spring:
  application:
    name: spring-demo-08-boot-webmvc-consuming-restapi
  
  thymeleaf:
    cache: false
    suffix: .html

  cloud:
    openfeign:
      client:
        config:
          contactsClient:
            url: http://localhost:9999/contacts